"""update dataBase

Revision ID: 5014ec2b82b6
Revises: 7f8f740696e2
Create Date: 2026-06-16 21:36:45.497218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5014ec2b82b6'
down_revision: Union[str, Sequence[str], None] = '7f8f740696e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupons', sa.Column('fraud_score', sa.Float(), nullable=True))
    op.add_column('coupons', sa.Column('processed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coupons', 'processed_at')
    op.drop_column('coupons', 'fraud_score')
    # ### end Alembic commands ###
