"""update 

Revision ID: 7f8f740696e2
Revises: 9c65cd05a17a
Create Date: 2026-06-16 21:36:29.014046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f8f740696e2'
down_revision: Union[str, Sequence[str], None] = '9c65cd05a17a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coupons', 'processed_at')
    op.drop_column('coupons', 'fraud_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupons', sa.Column('fraud_score', sa.FLOAT(), nullable=True))
    op.add_column('coupons', sa.Column('processed_at', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
